export const ADD_NEW = 'ADD_NEW';
export const UPDATE_CREDENTIAL = 'UPDATE_CREDENTIAL';
export const REMOVE_CREDENTIAL = 'REMOVE_CREDENTIAL';

export const REFRESH = 'REFRESH';

export const ROUTE = 'ROUTE';

export const SEND_ANOTHER_ONE = 'SEND_ANOTHER_ONE';

export const SAVE_AS_NEW_TEMPLATE = 'SAVE_AS_NEW_TEMPLATE';
export const USE_TEMPLATE = 'USE_TEMPLATE';
export const CURRENT_DATA = 'CURRENT_DATA';
export const SAVE_AND_EXIT = 'SAVE_AND_EXIT';

export const CLOSE = 'CLOSE';

export const EDIT_APP = 'EDIT_APP';

export const CREDENTIAL_CHANGED = 'CREDENTIAL_CHANGED';

export const OPEN_IN_PROGRESS_MODAL = 'OPEN_IN_PROGRESS_MODAL';

export const EDIT_FIELD = 'EDIT_FIELD';

export const REFETCH_SELECT = 'REFETCH_SELECT';

export const SELECT_TOUCHPOINT = 'SELECT_TOUCHPOINT';

export const OPEN_SELECT_TOUCHPOINT = 'OPEN_SELECT_TOUCHPOINT';

export const ADD_NEW_AI_ASSISTANT = 'ADD_NEW_AI_ASSISTANT';

export const UPDATE_AI_ASSISTANT = 'UPDATE_AI_ASSISTANT';

export const REMOVE_AI_ASSISTANT = 'REMOVE_AI_ASSISTANT';

export const REFRESH_AI_ASSISTANT = 'REFRESH_AI_ASSISTANT';

export const OPEN_SUPPORT_CENTER = 'OPEN_SUPPORT_CENTER';

export const SET_LANGUAGE = 'SET_LANGUAGE';

export const OPEN_UNLOCK_FEATURE = 'OPEN_UNLOCK_FEATURE';

export const DUPLICATION_FOUND = 'DUPLICATION_FOUND';

export const SKIP = 'SKIP';
export const CREATE_NEW = 'CREATE_NEW';
export const EDIT_FORM_HEADER = 'EDIT_FORM_HEADER';

export const ADD_FORM_FIELD = 'ADD_FORM_FIELD';

export const EDIT_FORM_FIELD = 'EDIT_FORM_FIELD';

export const EDIT_FORM_FOOTER = 'EDIT_FORM_FOOTER';

export const OPEN_STARTER = 'OPEN_STARTER';

export const OPEN_SHARE = 'OPEN_SHARE';

export const DELETE_FORM = 'DELETE_FORM';

export const SET_BREADCRUMB = 'SET_BREADCRUMB';

export const CHANGE_STEP = 'CHANGE_STEP';

export const BOARD_ACCESS_WARNING = 'BOARD_ACCESS_WARNING';

export const NOT_ABLE_TO_SAVE = 'NOT_ABLE_TO_SAVE';
export const SAVE_AND_EXIT_BEFORE_CLOSE = 'SAVE_AND_EXIT_BEFORE_CLOSE';
export const NOT_ABLE_TO_SAVE_BEFORE_CLOSE = 'NOT_ABLE_TO_SAVE_BEFORE_CLOSE';
export const EMAIL_CAMPAIGN_TYPE = {
    INSTANCE: 'instance',
    SCHEDULE: 'schedule',
};
export const DELETE_AI_ASSISTANT = 'DELETE_AI_ASSISTANT';
export const BACK_TO_MENU = 'BACK_TO_MENU';
export const OPEN_KNOWLEDGE_HUB = 'OPEN_KNOWLEDGE_HUB';
export const OPEN_WORKFLOW_FUNCTIONS = 'OPEN_WORKFLOW_FUNCTIONS';
export const SELECT_KNOWLEDGE_HUB_BOARD = 'SELECT_KNOWLEDGE_HUB_BOARD';
export const SELECT_WORKFLOW_FUNCTIONS = 'SELECT_WORKFLOW_FUNCTIONS';
export const SHOW_CREATE_AI_ASSISTANT_SUCCESS = 'SHOW_CREATE_AI_ASSISTANT_SUCCESS';
export const SHOW_FINANCIAL_MANAGEMENT_FILE_ERROR = 'SHOW_FINANCIAL_MANAGEMENT_FILE_ERROR';
export const SHOW_FINANCIAL_MANAGEMENT_FILE_CONTENT = 'SHOW_FINANCIAL_MANAGEMENT_FILE_CONTENT';
export const ADD_NEW_COLUMN_TO_FINANCIAL_FILE = 'ADD_NEW_COLUMN_TO_FINANCIAL_FILE';
export const EDIT_FINANCIAL_MANAGEMENT_FILE = 'EDIT_FINANCIAL_MANAGEMENT_FILE';
export const DELETE_FINANCIAL_MANAGEMENT_FILE = 'DELETE_FINANCIAL_MANAGEMENT_FILE';
export const RESET_FINANCIAL_FILE = 'RESET_FINANCIAL_FILE';