export const dummyCRMBoards: API.Board[] = [
    {
        _id: 'sample_contacts_boards',
        doc_name: 'boards',
        business_unit_id: 'bu_imbrace_testing',
        organization_id: 'org_imbrace',
        name: 'Contacts',
        description: '',
        type: 'Contacts',
        fields: [
            {
                name: 'Name',
                description: '',
                type: 'ShortText',
                is_unique_identifier: false,
                is_default: true,
                default_field_name: 'name',
                hidden: false,
                contact_field: 'display_name',
                is_identifier: true,
                _id: 'sample_name_field',
                data: [],
            },
            {
                name: 'Birthday',
                description: '',
                type: 'Date',
                is_unique_identifier: false,
                is_default: true,
                default_field_name: 'birthday',
                hidden: false,
                contact_field: 'birthday',
                data: [],
                _id: 'sample_birthday_field',
            },
            {
                name: 'Location',
                type: 'ShortText',
                is_unique_identifier: false,
                is_default: true,
                default_field_name: 'location',
                hidden: false,
                contact_field: 'location',
                _id: 'sample_location_field',
                data: [],
            },
            {
                name: 'Last Active',
                description: '',
                type: 'Date',
                is_unique_identifier: false,
                is_default: true,
                default_field_name: 'last_seen',
                hidden: false,
                contact_field: 'last_seen',
                _id: 'sample_last_active_field',
                data: [],
            },
            {
                name: 'Joined Since',
                description: '',
                type: 'Date',
                is_unique_identifier: false,
                is_default: true,
                default_field_name: 'created_at',
                hidden: false,
                contact_field: 'created_at',
                _id: 'sample_joined_since_field',
                data: [],
            },
            {
                name: 'Stage',
                description: '',
                type: 'SingleSelection',
                is_unique_identifier: false,
                is_default: true,
                default_field_name: 'stage',
                hidden: false,
                data: [
                    {
                        value: 'Unidentified Lead',
                        _id: 'Unidentified Lead',
                    },
                    {
                        value: 'Identified Lead',
                        _id: 'Identified Lead',
                    },
                    {
                        value: 'Prospect',
                        _id: 'Prospect',
                    },
                    {
                        value: 'Advocator',
                        _id: 'Advocator',
                    },
                    {
                        value: 'Customer',
                        _id: 'Customer',
                    },
                    {
                        value: 'Contact',
                        _id: 'Contact',
                    },
                    {
                        value: 'Disqualified',
                        _id: 'Disqualified',
                    },
                    {
                        value: 'Retention',
                        _id: 'Retention',
                    },
                ],
                _id: 'sample_stage_field',
            },
            {
                name: 'Tags',
                description: '',
                type: 'MultipleSelection',
                is_unique_identifier: false,
                is_default: true,
                default_field_name: 'tags',
                hidden: false,
                data: [
                    {
                        value: 'New Customer',
                        _id: 'New Customer',
                    },
                    {
                        value: 'Follow-up Needed',
                        _id: 'Follow-up Needed',
                    },
                ],
                _id: 'sample_tags_field',
            },
        ],
        public_id: 'sample_contacts_boards',
        created_at: '2023-07-25T08:59:15.982Z',
        updated_at: '2024-02-05T07:50:37.250Z',
        hidden: false,
        order: 1,
        id: 'sample_contacts_boards',
    },
    {
        _id: 'sample_companies_boards',
        doc_name: 'boards',
        business_unit_id: 'bu_imbrace_testing',
        organization_id: 'org_imbrace',
        name: 'Companies',
        description: '',
        type: 'Companies',
        fields: [
            {
                name: 'Name',
                description: '',
                type: 'ShortText',
                is_unique_identifier: false,
                is_default: true,
                default_field_name: 'name',
                hidden: false,
                contact_field: 'display_name',
                is_identifier: true,
                _id: 'sample_name_field',
                data: [],
            },
            {
                name: 'Birthday',
                description: '',
                type: 'Date',
                is_unique_identifier: false,
                is_default: true,
                default_field_name: 'birthday',
                hidden: false,
                contact_field: 'birthday',
                data: [],
                _id: 'sample_birthday_field',
            },
            {
                name: 'Location',
                type: 'ShortText',
                is_unique_identifier: false,
                is_default: true,
                default_field_name: 'location',
                hidden: false,
                contact_field: 'location',
                _id: 'sample_location_field',
                data: [],
            },
            {
                name: 'Last Active',
                description: '',
                type: 'Date',
                is_unique_identifier: false,
                is_default: true,
                default_field_name: 'last_seen',
                hidden: false,
                contact_field: 'last_seen',
                _id: 'sample_last_active_field',
                data: [],
            },
            {
                name: 'Joined Since',
                description: '',
                type: 'Date',
                is_unique_identifier: false,
                is_default: true,
                default_field_name: 'created_at',
                hidden: false,
                contact_field: 'created_at',
                _id: 'sample_joined_since_field',
                data: [],
            },
            {
                name: 'Stage',
                description: '',
                type: 'SingleSelection',
                is_unique_identifier: false,
                is_default: true,
                default_field_name: 'stage',
                hidden: false,
                data: [
                    {
                        value: 'Unidentified Lead',
                        _id: 'Unidentified Lead',
                    },
                    {
                        value: 'Identified Lead',
                        _id: 'Identified Lead',
                    },
                    {
                        value: 'Prospect',
                        _id: 'Prospect',
                    },
                    {
                        value: 'Advocator',
                        _id: 'Advocator',
                    },
                    {
                        value: 'Customer',
                        _id: 'Customer',
                    },
                    {
                        value: 'Contact',
                        _id: 'Contact',
                    },
                    {
                        value: 'Disqualified',
                        _id: 'Disqualified',
                    },
                    {
                        value: 'Retention',
                        _id: 'Retention',
                    },
                ],
                _id: 'sample_stage_field',
            },
            {
                name: 'Tags',
                description: '',
                type: 'MultipleSelection',
                is_unique_identifier: false,
                is_default: true,
                default_field_name: 'tags',
                hidden: false,
                data: [
                    {
                        value: 'New Customer',
                        _id: 'New Customer',
                    },
                    {
                        value: 'Follow-up Needed',
                        _id: 'Follow-up Needed',
                    },
                ],
                _id: 'sample_tags_field',
            },
        ],
        public_id: 'sample_companies_boards',
        created_at: '2023-07-25T08:59:15.982Z',
        updated_at: '2024-02-05T07:50:37.250Z',
        hidden: false,
        order: 2,
        id: 'sample_companies_boards',
    },
    {
        _id: 'sample_opportunities_boards',
        doc_name: 'boards',
        business_unit_id: 'bu_imbrace_testing',
        organization_id: 'org_imbrace',
        name: 'Opportunities',
        description: '',
        type: 'Opportunities',
        fields: [
            {
                name: 'Name',
                description: '',
                type: 'ShortText',
                is_unique_identifier: false,
                is_default: true,
                default_field_name: 'name',
                hidden: false,
                contact_field: 'display_name',
                is_identifier: true,
                _id: 'sample_name_field',
                data: [],
            },
            {
                name: 'Birthday',
                description: '',
                type: 'Date',
                is_unique_identifier: false,
                is_default: true,
                default_field_name: 'birthday',
                hidden: false,
                contact_field: 'birthday',
                data: [],
                _id: 'sample_birthday_field',
            },
            {
                name: 'Location',
                type: 'ShortText',
                is_unique_identifier: false,
                is_default: true,
                default_field_name: 'location',
                hidden: false,
                contact_field: 'location',
                _id: 'sample_location_field',
                data: [],
            },
            {
                name: 'Last Active',
                description: '',
                type: 'Date',
                is_unique_identifier: false,
                is_default: true,
                default_field_name: 'last_seen',
                hidden: false,
                contact_field: 'last_seen',
                _id: 'sample_last_active_field',
                data: [],
            },
            {
                name: 'Joined Since',
                description: '',
                type: 'Date',
                is_unique_identifier: false,
                is_default: true,
                default_field_name: 'created_at',
                hidden: false,
                contact_field: 'created_at',
                _id: 'sample_joined_since_field',
                data: [],
            },
            {
                name: 'Stage',
                description: '',
                type: 'SingleSelection',
                is_unique_identifier: false,
                is_default: true,
                default_field_name: 'stage',
                hidden: false,
                data: [
                    {
                        value: 'Unidentified Lead',
                        _id: 'Unidentified Lead',
                    },
                    {
                        value: 'Identified Lead',
                        _id: 'Identified Lead',
                    },
                    {
                        value: 'Prospect',
                        _id: 'Prospect',
                    },
                    {
                        value: 'Advocator',
                        _id: 'Advocator',
                    },
                    {
                        value: 'Customer',
                        _id: 'Customer',
                    },
                    {
                        value: 'Contact',
                        _id: 'Contact',
                    },
                    {
                        value: 'Disqualified',
                        _id: 'Disqualified',
                    },
                    {
                        value: 'Retention',
                        _id: 'Retention',
                    },
                ],
                _id: 'sample_stage_field',
            },
            {
                name: 'Tags',
                description: '',
                type: 'MultipleSelection',
                is_unique_identifier: false,
                is_default: true,
                default_field_name: 'tags',
                hidden: false,
                data: [
                    {
                        value: 'New Customer',
                        _id: 'New Customer',
                    },
                    {
                        value: 'Follow-up Needed',
                        _id: 'Follow-up Needed',
                    },
                ],
                _id: 'sample_tags_field',
            },
        ],
        public_id: 'sample_opportunities_boards',
        created_at: '2023-07-25T08:59:15.982Z',
        updated_at: '2024-02-05T07:50:37.250Z',
        hidden: false,
        order: 3,
        id: 'sample_opportunities_boards',
    },
    {
        _id: 'sample_tasks_boards',
        doc_name: 'boards',
        business_unit_id: 'bu_imbrace_testing',
        organization_id: 'org_imbrace',
        name: 'Tasks',
        description: '',
        type: 'Tasks',
        fields: [
            {
                name: 'Name',
                description: '',
                type: 'ShortText',
                is_unique_identifier: false,
                is_default: true,
                default_field_name: 'name',
                hidden: false,
                contact_field: 'display_name',
                is_identifier: true,
                _id: 'sample_name_field',
                data: [],
            },
            {
                name: 'Birthday',
                description: '',
                type: 'Date',
                is_unique_identifier: false,
                is_default: true,
                default_field_name: 'birthday',
                hidden: false,
                contact_field: 'birthday',
                data: [],
                _id: 'sample_birthday_field',
            },
            {
                name: 'Location',
                type: 'ShortText',
                is_unique_identifier: false,
                is_default: true,
                default_field_name: 'location',
                hidden: false,
                contact_field: 'location',
                _id: 'sample_location_field',
                data: [],
            },
            {
                name: 'Last Active',
                description: '',
                type: 'Date',
                is_unique_identifier: false,
                is_default: true,
                default_field_name: 'last_seen',
                hidden: false,
                contact_field: 'last_seen',
                _id: 'sample_last_active_field',
                data: [],
            },
            {
                name: 'Joined Since',
                description: '',
                type: 'Date',
                is_unique_identifier: false,
                is_default: true,
                default_field_name: 'created_at',
                hidden: false,
                contact_field: 'created_at',
                _id: 'sample_joined_since_field',
                data: [],
            },
            {
                name: 'Stage',
                description: '',
                type: 'SingleSelection',
                is_unique_identifier: false,
                is_default: true,
                default_field_name: 'stage',
                hidden: false,
                data: [
                    {
                        value: 'Unidentified Lead',
                        _id: 'Unidentified Lead',
                    },
                    {
                        value: 'Identified Lead',
                        _id: 'Identified Lead',
                    },
                    {
                        value: 'Prospect',
                        _id: 'Prospect',
                    },
                    {
                        value: 'Advocator',
                        _id: 'Advocator',
                    },
                    {
                        value: 'Customer',
                        _id: 'Customer',
                    },
                    {
                        value: 'Contact',
                        _id: 'Contact',
                    },
                    {
                        value: 'Disqualified',
                        _id: 'Disqualified',
                    },
                    {
                        value: 'Retention',
                        _id: 'Retention',
                    },
                ],
                _id: 'sample_stage_field',
            },
            {
                name: 'Tags',
                description: '',
                type: 'MultipleSelection',
                is_unique_identifier: false,
                is_default: true,
                default_field_name: 'tags',
                hidden: false,
                data: [
                    {
                        value: 'New Customer',
                        _id: 'New Customer',
                    },
                    {
                        value: 'Follow-up Needed',
                        _id: 'Follow-up Needed',
                    },
                ],
                _id: 'sample_tags_field',
            },
        ],
        public_id: 'sample_tasks_boards',
        created_at: '2023-07-25T08:59:15.982Z',
        updated_at: '2024-02-05T07:50:37.250Z',
        hidden: false,
        order: 5,
        id: 'sample_tasks_boards',
    },
    {
        _id: 'sample_products_boards',
        doc_name: 'boards',
        business_unit_id: 'bu_imbrace_testing',
        organization_id: 'org_imbrace',
        name: 'Products',
        description: '',
        type: 'Products',
        fields: [
            {
                name: 'Name',
                description: '',
                type: 'ShortText',
                is_unique_identifier: false,
                is_default: true,
                default_field_name: 'name',
                hidden: false,
                contact_field: 'display_name',
                is_identifier: true,
                _id: 'sample_name_field',
                data: [],
            },
            {
                name: 'Birthday',
                description: '',
                type: 'Date',
                is_unique_identifier: false,
                is_default: true,
                default_field_name: 'birthday',
                hidden: false,
                contact_field: 'birthday',
                data: [],
                _id: 'sample_birthday_field',
            },
            {
                name: 'Location',
                type: 'ShortText',
                is_unique_identifier: false,
                is_default: true,
                default_field_name: 'location',
                hidden: false,
                contact_field: 'location',
                _id: 'sample_location_field',
                data: [],
            },
            {
                name: 'Last Active',
                description: '',
                type: 'Date',
                is_unique_identifier: false,
                is_default: true,
                default_field_name: 'last_seen',
                hidden: false,
                contact_field: 'last_seen',
                _id: 'sample_last_active_field',
                data: [],
            },
            {
                name: 'Joined Since',
                description: '',
                type: 'Date',
                is_unique_identifier: false,
                is_default: true,
                default_field_name: 'created_at',
                hidden: false,
                contact_field: 'created_at',
                _id: 'sample_joined_since_field',
                data: [],
            },
            {
                name: 'Stage',
                description: '',
                type: 'SingleSelection',
                is_unique_identifier: false,
                is_default: true,
                default_field_name: 'stage',
                hidden: false,
                data: [
                    {
                        value: 'Unidentified Lead',
                        _id: 'Unidentified Lead',
                    },
                    {
                        value: 'Identified Lead',
                        _id: 'Identified Lead',
                    },
                    {
                        value: 'Prospect',
                        _id: 'Prospect',
                    },
                    {
                        value: 'Advocator',
                        _id: 'Advocator',
                    },
                    {
                        value: 'Customer',
                        _id: 'Customer',
                    },
                    {
                        value: 'Contact',
                        _id: 'Contact',
                    },
                    {
                        value: 'Disqualified',
                        _id: 'Disqualified',
                    },
                    {
                        value: 'Retention',
                        _id: 'Retention',
                    },
                ],
                _id: 'sample_stage_field',
            },
            {
                name: 'Tags',
                description: '',
                type: 'MultipleSelection',
                is_unique_identifier: false,
                is_default: true,
                default_field_name: 'tags',
                hidden: false,
                data: [
                    {
                        value: 'New Customer',
                        _id: 'New Customer',
                    },
                    {
                        value: 'Follow-up Needed',
                        _id: 'Follow-up Needed',
                    },
                ],
                _id: 'sample_tags_field',
            },
        ],
        public_id: 'sample_products_boards',
        created_at: '2023-07-25T08:59:15.982Z',
        updated_at: '2024-02-05T07:50:37.250Z',
        hidden: false,
        order: 6,
        id: 'sample_products_boards',
    },
];

export const dummyCRMBoardItems: API.BoardItem[] = [
    {
        id: 'sample_board_item_jenny',
        board: dummyCRMBoards[0],
        sample_name_field: 'Jenny Wong',
        sample_birthday_field: '1997/02/23',
        sample_location_field: 'Hong Kong',
        sample_stage_field: 'Prospect',
        sample_last_active_field: `${new Date().toISOString()}`,
        sample_joined_since_field: `${new Date().toISOString()}`,
        sample_tags_field: ['New Customer', 'Follow-up Needed'],
        board_item_id: 'sample_board_item_jenny',
        board_id: 'sample_contacts_boards',
        doc_name: 'boards item',
        business_unit_id: 'bu_imbrace_testing',
        contact_id: 'sample_contact_jenny',
        created_at: `${new Date().toISOString()}`,
        created_type: 'system',
        conversation_ids: [],
        fields: {
            sample_name_field: 'Jenny Wong',
            sample_birthday_field: '1997/02/23',
            sample_location_field: 'Hong Kong',
            sample_stage_field: 'Prospect',
            sample_last_active_field: `${new Date().toISOString()}`,
            sample_joined_since_field: `${new Date().toISOString()}`,
            sample_tags_field: ['New Customer', 'Follow-up Needed'],
        },
        public_id: 'sample_board_item_jenny',
        updated_at: `${new Date().toISOString()}`,
        organization_id: 'sample_organization',
        _id: 'sample_board_item_jenny',
    } as API.BoardItem,
];

export const dummyBoards: API.Board[] = [
    {
        _id: 'sample_general_board1',
        doc_name: 'boards',
        business_unit_id: 'bu_imbrace_testing',
        organization_id: 'org_imbrace',
        name: 'Email Outbound Records',
        description: 'Email Outbound Records',
        type: 'General',
        fields: [
            {
                name: 'Email',
                description: '',
                type: 'Email',
                is_unique_identifier: false,
                is_default: true,
                default_field_name: 'email',
                hidden: false,
                is_identifier: true,
                _id: 'sample_email_field',
                data: [],
            },
            {
                name: 'Outbound Source',
                description: '',
                type: 'Email',
                is_unique_identifier: false,
                is_default: true,
                default_field_name: 'Outbound Source',
                hidden: false,
                data: [],
                _id: 'sample_outbound_source_field',
            },
            {
                name: 'Email Content',
                type: 'RichText',
                is_unique_identifier: false,
                is_default: true,
                default_field_name: 'Email Content',
                hidden: false,
                _id: 'sample_email_content_field',
                data: [],
            },
            {
                name: 'Outbound Status',
                description: '',
                type: 'SingleSelection',
                is_unique_identifier: false,
                is_default: true,
                default_field_name: 'Outbound Status',
                hidden: false,
                _id: 'sample_outbound_status_field',
                data: [
                    {
                        _id: 'Pending',
                        value: 'Pending',
                    },
                    {
                        _id: 'Success',
                        value: 'Success',
                    },
                ],
            },
            {
                name: 'Sent Date',
                description: '',
                type: 'Date',
                is_unique_identifier: false,
                is_default: true,
                default_field_name: 'Sent Date',
                hidden: false,
                _id: 'sample_sent_date_field',
                data: [],
            },
            {
                name: 'Sent Time',
                description: '',
                type: 'Time',
                is_unique_identifier: false,
                is_default: true,
                default_field_name: 'Sent Time',
                hidden: false,
                data: [],
                _id: 'sample_send_time_field',
            },
            {
                name: 'Sent By',
                description: '',
                type: 'Assignee',
                is_unique_identifier: false,
                is_default: true,
                default_field_name: 'Sent By',
                hidden: false,
                data: [],
                _id: 'sample_send_by_field',
            },
        ],
        public_id: 'sample_general_board1',
        created_at: '2023-07-25T08:59:15.982Z',
        updated_at: '2024-02-05T07:50:37.250Z',
        hidden: false,
        order: 1,
        id: 'sample_general_board1',
    },
    {
        _id: 'sample_general_board2',
        doc_name: 'boards',
        business_unit_id: 'bu_imbrace_testing',
        organization_id: 'org_imbrace',
        name: 'Whatsapp Outbound Records',
        description: '',
        type: 'General',
        fields: [
            {
                name: 'Email',
                description: '',
                type: 'Email',
                is_unique_identifier: false,
                is_default: true,
                default_field_name: 'email',
                hidden: false,
                is_identifier: true,
                _id: 'sample_email_field',
                data: [],
            },
            {
                name: 'Outbound Source',
                description: '',
                type: 'Email',
                is_unique_identifier: false,
                is_default: true,
                default_field_name: 'Outbound Source',
                hidden: false,
                data: [],
                _id: 'sample_outbound_source_field',
            },
            {
                name: 'Email Content',
                type: 'RichText',
                is_unique_identifier: false,
                is_default: true,
                default_field_name: 'Email Content',
                hidden: false,
                _id: 'sample_email_content_field',
                data: [],
            },
            {
                name: 'Outbound Status',
                description: '',
                type: 'SingleSelection',
                is_unique_identifier: false,
                is_default: true,
                default_field_name: 'Outbound Status',
                hidden: false,
                _id: 'sample_outbound_status_field',
                data: [
                    {
                        _id: 'Pending',
                        value: 'Pending',
                    },
                    {
                        _id: 'Success',
                        value: 'Success',
                    },
                ],
            },
            {
                name: 'Sent Date',
                description: '',
                type: 'Date',
                is_unique_identifier: false,
                is_default: true,
                default_field_name: 'Sent Date',
                hidden: false,
                _id: 'sample_sent_date_field',
                data: [],
            },
            {
                name: 'Sent Time',
                description: '',
                type: 'Time',
                is_unique_identifier: false,
                is_default: true,
                default_field_name: 'Sent Time',
                hidden: false,
                data: [],
                _id: 'sample_send_time_field',
            },
            {
                name: 'Sent By',
                description: '',
                type: 'Assignee',
                is_unique_identifier: false,
                is_default: true,
                default_field_name: 'Sent By',
                hidden: false,
                data: [],
                _id: 'sample_send_by_field',
            },
        ],
        public_id: 'sample_general_board2',
        created_at: '2023-07-25T08:59:15.982Z',
        updated_at: '2024-02-05T07:50:37.250Z',
        hidden: false,
        order: 2,
        id: 'sample_general_board2',
    },
    {
        _id: 'sample_general_board3',
        doc_name: 'boards',
        business_unit_id: 'bu_imbrace_testing',
        organization_id: 'org_imbrace',
        name: 'Facebook Comment',
        description: '',
        type: 'General',
        fields: [
            {
                name: 'Email',
                description: '',
                type: 'Email',
                is_unique_identifier: false,
                is_default: true,
                default_field_name: 'email',
                hidden: false,
                is_identifier: true,
                _id: 'sample_email_field',
                data: [],
            },
            {
                name: 'Outbound Source',
                description: '',
                type: 'Email',
                is_unique_identifier: false,
                is_default: true,
                default_field_name: 'Outbound Source',
                hidden: false,
                data: [],
                _id: 'sample_outbound_source_field',
            },
            {
                name: 'Email Content',
                type: 'RichText',
                is_unique_identifier: false,
                is_default: true,
                default_field_name: 'Email Content',
                hidden: false,
                _id: 'sample_email_content_field',
                data: [],
            },
            {
                name: 'Outbound Status',
                description: '',
                type: 'SingleSelection',
                is_unique_identifier: false,
                is_default: true,
                default_field_name: 'Outbound Status',
                hidden: false,
                _id: 'sample_outbound_status_field',
                data: [
                    {
                        _id: 'Pending',
                        value: 'Pending',
                    },
                    {
                        _id: 'Success',
                        value: 'Success',
                    },
                ],
            },
            {
                name: 'Sent Date',
                description: '',
                type: 'Date',
                is_unique_identifier: false,
                is_default: true,
                default_field_name: 'Sent Date',
                hidden: false,
                _id: 'sample_sent_date_field',
                data: [],
            },
            {
                name: 'Sent Time',
                description: '',
                type: 'Time',
                is_unique_identifier: false,
                is_default: true,
                default_field_name: 'Sent Time',
                hidden: false,
                data: [],
                _id: 'sample_send_time_field',
            },
            {
                name: 'Sent By',
                description: '',
                type: 'Assignee',
                is_unique_identifier: false,
                is_default: true,
                default_field_name: 'Sent By',
                hidden: false,
                data: [],
                _id: 'sample_send_by_field',
            },
        ],
        public_id: 'sample_general_board3',
        created_at: '2023-07-25T08:59:15.982Z',
        updated_at: '2024-02-05T07:50:37.250Z',
        hidden: false,
        order: 3,
        id: 'sample_general_board3',
    },
];

export const dummyBoardItems: API.BoardItem[] = [
    {
        id: 'sample_board_item_1',
        board: dummyBoards[0],
        sample_email_field: 'sample-4@gmail.com',
        sample_outbound_status_field: 'Pending',
        sample_email_content_field: {
            content: '<p>Hello, this is a test email.</p>',
        },
        sample_outbound_source_field: 'social@imbrace.co',
        sample_sent_date_field: `${new Date().toISOString()}`,
        sample_send_time_field: `${new Date().toISOString()}`,
        board_item_id: 'sample_board_item_1',
        board_id: 'sample_general_board1',
        doc_name: 'boards item',
        business_unit_id: 'bu_imbrace_testing',
        created_at: `${new Date().toISOString()}`,
        created_type: 'system',
        conversation_ids: [],
        fields: {
            sample_email_field: 'sample-4@gmail.com',
            sample_outbound_status_field: 'Pending',
            sample_email_content_field: {
                content: '<p>Hello, this is a test email.</p>',
            },
            sample_outbound_source_field: 'social@imbrace.co',
            sample_sent_date_field: `${new Date().toISOString()}`,
            sample_send_time_field: `${new Date().toISOString()}`,
        },
        public_id: 'sample_board_item_1',
        updated_at: `${new Date().toISOString()}`,
        organization_id: 'sample_organization',
        _id: 'sample_board_item_1',
    } as API.BoardItem,
    {
        id: 'sample_board_item_2',
        board: dummyBoards[0],
        sample_email_field: 'sample-3@gmail.com',
        sample_outbound_status_field: 'Success',
        sample_email_content_field: {
            content: '<p>Hello, this is a test email.</p>',
        },
        sample_outbound_source_field: 'social@imbrace.co',
        sample_sent_date_field: `${new Date().toISOString()}`,
        sample_send_time_field: `${new Date().toISOString()}`,
        board_item_id: 'sample_board_item_2',
        board_id: 'sample_general_board1',
        doc_name: 'boards item',
        business_unit_id: 'bu_imbrace_testing',
        created_at: `${new Date().toISOString()}`,
        created_type: 'system',
        conversation_ids: [],
        fields: {
            sample_email_field: 'sample-3@gmail.com',
            sample_outbound_status_field: 'Success',
            sample_email_content_field: {
                content: '<p>Hello, this is a test email.</p>',
            },
            sample_outbound_source_field: 'social@imbrace.co',
            sample_sent_date_field: `${new Date().toISOString()}`,
            sample_send_time_field: `${new Date().toISOString()}`,
        },
        public_id: 'sample_board_item_2',
        updated_at: `${new Date().toISOString()}`,
        organization_id: 'sample_organization',
        _id: 'sample_board_item_2',
    } as API.BoardItem,
    {
        id: 'sample_board_item_3',
        board: dummyBoards[0],
        sample_email_field: 'sample-2@gmail.com',
        sample_outbound_status_field: 'Success',
        sample_email_content_field: {
            content: '<p>Hello, this is a test email.</p>',
        },
        sample_outbound_source_field: 'marketing@imbrace.co',
        sample_sent_date_field: `${new Date().toISOString()}`,
        sample_send_time_field: `${new Date().toISOString()}`,
        board_item_id: 'sample_board_item_3',
        board_id: 'sample_general_board1',
        doc_name: 'boards item',
        business_unit_id: 'bu_imbrace_testing',
        created_at: `${new Date().toISOString()}`,
        created_type: 'system',
        conversation_ids: [],
        fields: {
            sample_email_field: 'sample-2@gmail.com',
            sample_outbound_status_field: 'Success',
            sample_email_content_field: {
                content: '<p>Hello, this is a test email.</p>',
            },
            sample_outbound_source_field: 'marketing@imbrace.co',
            sample_sent_date_field: `${new Date().toISOString()}`,
            sample_send_time_field: `${new Date().toISOString()}`,
        },
        public_id: 'sample_board_item_3',
        updated_at: `${new Date().toISOString()}`,
        organization_id: 'sample_organization',
        _id: 'sample_board_item_3',
    } as API.BoardItem,
    {
        id: 'sample_board_item_4',
        board: dummyBoards[0],
        sample_email_field: 'sample-1@gmail.com',
        sample_outbound_status_field: 'Success',
        sample_email_content_field: {
            content: '<p>Hello, this is a test email.</p>',
        },
        sample_outbound_source_field: 'marketing@imbrace.co',
        sample_sent_date_field: `${new Date().toISOString()}`,
        sample_send_time_field: `${new Date().toISOString()}`,
        board_item_id: 'sample_board_item_4',
        board_id: 'sample_general_board1',
        doc_name: 'boards item',
        business_unit_id: 'bu_imbrace_testing',
        created_at: `${new Date().toISOString()}`,
        created_type: 'system',
        conversation_ids: [],
        fields: {
            sample_email_field: 'sample-1@gmail.com',
            sample_outbound_status_field: 'Success',
            sample_email_content_field: {
                content: '<p>Hello, this is a test email.</p>',
            },
            sample_outbound_source_field: 'marketing@imbrace.co',
            sample_sent_date_field: `${new Date().toISOString()}`,
            sample_send_time_field: `${new Date().toISOString()}`,
        },
        public_id: 'sample_board_item_4',
        updated_at: `${new Date().toISOString()}`,
        organization_id: 'sample_organization',
        _id: 'sample_board_item_4',
    } as API.BoardItem,
];
