// import * as React from "react";

export const memberDetailsRequiredFields = [
    {
        name: 'display_name',
        type: 'input',
        label: 'Nickname',
        i18: 'form_display_name',
        placeholder: '',
        editable: true,
    },
    {
        name: 'first_name',
        type: 'input',
        label: 'First Name',
        i18: 'form_first_name',
        placeholder: '',
        editable: true,
    },
    {
        name: 'last_name',
        type: 'input',
        label: 'Last Name',
        i18: 'form_last_name',
        placeholder: '',
        editable: true,
    },
    {
        name: 'phone_number',
        type: 'input',
        label: 'Phone no.',
        i18: 'form_phone_number',
        placeholder: '',
        editable: true,
    },
    {
        name: 'gender',
        type: 'select',
        options: [
            { label: '-', i18: '-', value: '' },
            { label: 'Male', i18: 'form_gender_male', value: 'm' },
            { label: 'Female', i18: 'form_gender_female', value: 'f' },
        ],
        label: 'Gender',
        i18: 'form_gender',
        placeholder: '',
        editable: true,
    },
    {
        name: 'email',
        type: 'input',
        label: 'Email',
        i18: 'form_email',
        placeholder: '',
        editable: true,
    },
    {
        name: 'language',
        type: 'select',
        options: [
            { label: '-', value: '', i18: '-' },
            { label: 'English', value: 'en', i18: 'form_language_en' },
            { label: 'Chinese (Traditional)', value: 'zh', i18: 'form_language_zh' },
            { label: 'Chinese (Simplified)', value: 'cn', i18: 'form_language_cn' },
        ],
        label: 'Language',
        i18: 'form_language',
        placeholder: '',
        editable: true,
    },
];

export const contactRequiredFields = [
    {
        name: 'display_name',
        type: 'input',
        label: 'Nickname',
        i18: 'form_display_name',
        placeholder: '',
        editable: false,
    },
    {
        name: 'first_name',
        type: 'input',
        label: 'First Name',
        i18: 'form_first_name',
        placeholder: '',
        editable: true,
    },
    {
        name: 'last_name',
        type: 'input',
        label: 'Last Name',
        i18: 'form_last_name',
        placeholder: '',
        editable: true,
    },
    {
        name: 'phone_number',
        type: 'input',
        label: 'Phone no.',
        i18: 'form_phone_number',
        placeholder: '',
        editable: true,
    },
    {
        name: 'gender',
        type: 'select',
        options: [
            { label: '-', i18: '-', value: '' },
            { label: 'Male', i18: 'form_gender_male', value: 'm' },
            { label: 'Female', i18: 'form_gender_female', value: 'f' },
        ],
        label: 'Gender',
        i18: 'form_gender',
        placeholder: '-',
        editable: true,
    },
    // {
    //     name: 'area_code',
    //     type: 'select',
    //     options: [
    //         { label: '-', i18: '-', value: '' },
    //         { label: 'HK', i18: 'form_region_hk', value: '852' },
    //     ],
    //     label: 'Region',
    //     i18: 'chatroom_userprofile_region',
    //     placeholder: '',
    //     editable: true,
    // },
    {
        name: 'email',
        type: 'input',
        label: 'Email',
        i18: 'form_email',
        placeholder: '',
        editable: true,
    },
    {
        name: 'time_zone',
        type: 'input',
        label: 'Timezone',
        i18: 'form_time_zone',
        placeholder: '',
        editable: false,
    },
    {
        name: 'language',
        type: 'select',
        options: [
            { label: '-', value: '', i18: '-' },
            { label: 'English', value: 'en', i18: 'form_language_en' },
            { label: 'Chinese (Traditional)', value: 'zh', i18: 'form_language_zh' },
            { label: 'Chinese (Simplified)', value: 'cn', i18: 'form_language_cn' },
        ],
        label: 'Language',
        i18: 'form_language',
        placeholder: '',
        editable: true,
    },
    {
        name: 'remark',
        type: 'input',
        label: 'Remarks',
        i18: 'form_remarks',
        placeholder: '',
        editable: true,
    },
    // {
    //     name: 'channel_type',
    //     type: 'select',
    //     options: [
    //         { label: '-', value: '', i18: '-' },
    //         { label: 'Web', value: 'web', i18: 'Web' },
    //         { label: 'Instagram', value: 'instagram', i18: 'Instagram' },
    //         { label: 'Facebook', value: 'facebook', i18: 'Facebook' },
    //         { label: 'Whatsapp', value: 'whatsapp', i18: 'Whatsapp' },
    //     ],
    //     label: 'Channels',
    //     i18: 'chatroom_userprofile_channels',
    //     placeholder: '',
    //     editable: false,
    // },
];

export const teamMemberRequiredFields = [
    {
        name: 'first_name',
        type: 'input',
        label: 'First Name',
        i18: 'form_first_name',
        placeholder: '',
        editable: true,
    },
    {
        name: 'last_name',
        type: 'input',
        label: 'Last Name',
        i18: 'form_last_name',
        placeholder: '',
        editable: true,
    },
    // {
    //     name: 'display_name',
    //     type: 'input',
    //     label: 'Nickname',
    //     i18: 'form_display_name',
    //     placeholder: '',
    //     editable: false,
    // },
    {
        name: 'role',
        type: 'select',
        options: [
            { label: '-', i18: '-', value: '' },
            { label: 'Admin', i18: 'form_team_role_admin', value: 'admin' },
            { label: 'Representative', i18: 'form_team_role_agent', value: 'representative' },
        ],
        label: 'Team Role',
        i18: 'form_team_role',
        placeholder: '',
        editable: true,
    },
    {
        name: 'gender',
        type: 'select',
        options: [
            { label: '-', i18: '-', value: '' },
            { label: 'Male', i18: 'form_gender_male', value: 'm' },
            { label: 'Female', i18: 'form_gender_female', value: 'f' },
        ],
        label: 'Gender',
        i18: 'form_gender',
        placeholder: '-',
        editable: true,
    },
    {
        name: 'email',
        type: 'input',
        label: 'Email',
        i18: 'form_email',
        placeholder: '',
        editable: true,
    },
    // {
    //     name: 'time_zone',
    //     type: 'select',
    //     options: [
    //         { label: '-', i18: '-', value: '' },
    //         { label: 'HK', i18: 'form_region_hk', value: '852' },
    //     ],
    //     label: 'Region',
    //     i18: 'chatroom_userprofile_region',
    //     placeholder: '',
    //     editable: true,
    // },
    {
        name: 'created_at',
        type: 'input',
        label: 'Create Date',
        i18: 'form_create_date',
        placeholder: '',
        editable: false,
    },
    {
        name: 'language',
        type: 'select',
        options: [
            { label: '-', value: '', i18: '-' },
            { label: 'English', value: 'en', i18: 'form_language_en' },
            { label: 'Chinese (Traditional)', value: 'zh', i18: 'form_language_zh' },
            { label: 'Chinese (Simplified)', value: 'cn', i18: 'form_language_cn' },
        ],
        label: 'Language',
        i18: 'form_language',
        placeholder: '',
        editable: true,
    },
    // {
    //     name: 'job_title',
    //     type: 'input',
    //     label: 'Job Title',
    //     i18: 'form_team_job_title',
    //     placeholder: '',
    //     editable: true,
    // },
];

export const addAttributeFormFields = [
    {
        name: 'title',
        type: 'input',
        label: 'Title',
        i18: 'chatroom_userprofile_title',
        placeholder: '',
        editable: true,
    },
    {
        name: 'content',
        type: 'input',
        label: 'Content',
        i18: 'chatroom_userprofile_content',
        placeholder: '',
        editable: true,
    },
    {
        name: 'identifier',
        type: 'input',
        label: 'Identifier',
        i18: 'chatroom_userprofile_identifier',
        placeholder: '',
        editable: true,
    },
    {
        name: 'data-type',
        type: 'select',
        options: [
            { label: 'English', value: 'en', i18: 'form_language_en' },
            { label: 'Chinese (Traditional)', value: 'zh', i18: 'form_language_zh' },
            { label: 'Chinese (Simplified)', value: 'cn', i18: 'form_language_cn' },
        ],
        label: 'Data Type',
        i18: 'chatroom_userprofile_data_type',
        placeholder: '',
        editable: true,
    },
];
