/* eslint-disable no-restricted-globals */

// This service worker can be customized!
// See https://developers.google.com/web/tools/workbox/modules
// for the list of available Workbox modules, or add any other
// code you'd like.
// You can also remove this file if you'd prefer not to use a
// service worker, and the Workbox build step will be skipped.

import { clientsClaim } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate, NetworkFirst } from 'workbox-strategies';

clientsClaim();

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching. See https://cra.link/PWA
precacheAndRoute(self.__WB_MANIFEST.filter((file) => !file.url.includes('index.html')));

// Set up App Shell-style routing, so that all navigation requests
// are fulfilled with your index.html shell. Learn more at
// https://developers.google.com/web/fundamentals/architecture/app-shell
// const fileExtensionRegexp = new RegExp('/[^/?]+\\.[^/]+$');
// registerRoute(
//     // Return false to exempt requests from being fulfilled by index.html.
//     ({ request, url }) => {
//         // If this isn't a navigation, skip.
//         if (request.mode !== 'navigate') {
//             return false;
//         } // If this is a URL that starts with /_, skip.

//         if (url.pathname.startsWith('/_')) {
//             return false;
//         } // If this looks like a URL for a resource, because it contains // a file extension, skip.

//         if (url.pathname.match(fileExtensionRegexp)) {
//             return false;
//         } // Return true to signal that we want to use the handler.

//         return true;
//     },
//     createHandlerBoundToURL(env.PUBLIC_URL + '/index.html'),
// );
registerRoute(({ url }) => url.pathname.includes('index.html'), new NetworkFirst());

// An example runtime caching route for requests that aren't handled by the
// precache, in this case same-origin .png requests like those from in public/
registerRoute(
    // Add in any other file extensions or routing criteria as needed.
    ({ url }) => url.origin === self.location.origin && url.pathname.endsWith('.png'), // Customize this strategy as needed, e.g., by changing to CacheFirst.
    new StaleWhileRevalidate({
        cacheName: 'images',
        plugins: [
            // Ensure that once this runtime cache reaches a maximum size the
            // least-recently used images are removed.
            new ExpirationPlugin({ maxEntries: 50 }),
        ],
    }),
);

// This allows the web app to trigger skipWaiting via
// registration.waiting.postMessage({type: 'SKIP_WAITING'})
self.addEventListener('message', (event) => {
    if (event.data && event.data.type === 'SKIP_WAITING') {
        self.skipWaiting();
    }
});

// Any other custom service worker logic can go here.
// if ('function' === typeof importScripts) {
//     // Import Pushy Service Worker 1.0.8
//     // eslint-disable-next-line
//     importScripts('https://sdk.pushy.me/web/1.0.8/pushy-service-worker.js');
// }
// Listen for incoming push notifications
self.addEventListener('push', function (event) {
    // Extract payload as JSON object, default to empty object
    var data = event.data.json() || {};

    // Extract notification image URL
    var image = data.image || 'https://sdk.pushy.me/web/assets/img/icon.png';

    // Notification title and body
    var title = data.title || '';
    var body = data.message || '';

    // Notification options
    var options = {
        body: body,
        icon: image,
        badge: image,
        data,
    };

    // Support for notification collapsing
    if (data._pushyCollapseKey) options.tag = data._pushyCollapseKey;

    event.waitUntil(
        // eslint-disable-next-line
        clients
            .matchAll({
                type: 'window',
            })
            .then(function (clientList) {
                // check if webpage is open
                let clientIsVisible = false;
                for (let i = 0; i < clientList.length; i++) {
                    let client = clientList[i];
                    // console.log(client);
                    const { visibilityState } = client;
                    if (visibilityState === 'visible') {
                        clientIsVisible = true;
                    }
                    return clientIsVisible;
                }
            })
            .then((isVisible) => {
                // console.log('isVisible', isVisible);
                if (!isVisible) {
                    return event.waitUntil(self.registration.showNotification(title, options));
                }
                return;
            })
            .catch((error) => {
                console.log(error);
            }),
    );

    // console.log('isVisible', clientIsVisible);
    // if (!clientIsVisible) {
    //     // Wait until notification is shown
    //     event.waitUntil(self.registration.showNotification(title, options));
    // }

    // Send to Pushy notification listener (if webpage is open)
    // eslint-disable-next-line
    clients.matchAll().then((clients) => {
        // Set pushy notification flag
        data._pushy = true;

        // Send to all open pages
        clients.forEach((client) => {
            client.postMessage(data, [new MessageChannel().port2]);
        });
    });
});
// Listen for notification click event
self.addEventListener('notificationclick', function (event) {
    // Hide notification
    event.notification.close();
    let url = 'http://localhost:3001';

    if (import.meta.env.VITE_APP_ENV === 'prod') {
        url = 'https://app.imbrace.co';
    }
    if (import.meta.env.VITE_APP_ENV === 'staging') {
        url = 'http://localhost:3001';
    }
    if (import.meta.env.VITE_APP_ENV === 'demo') {
        url = 'http://localhost:3001';
    }

    const type = event.notification?.data.type;
    if (type === 'grab') {
        const id = event.notification?.data.id;
        if (id) {
            url = `${url}/chatroom?grab_id=${event.notification?.data.id}`;
        }
    } else {
        const conversation_id = event.notification?.data.conversation_id;
        if (conversation_id) {
            url = `${url}/chatroom?to_conv=${event.notification?.data.conversation_id}`;
        }
    }

    // Open the target URL in a new tab/window
    // eslint-disable-next-line
    event.waitUntil(clients.openWindow(url));
});
