import type { ReduxMessage } from '@/redux/slices/message.types';
import type { ReduxTeamConversations } from '@/redux/slices/teamConversation.types';

import DummyAvatar from './avatar.png';

export const dummyContact: API.Contact = {
    object_name: 'contact',
    _id: 'sample_contact',
    id: 'sample_contact',
    updated_at: '',
    created_at: '2024-01-26T06:27:00.234Z',
    business_unit_id: 'bu_imbrace_testing',
    organization_id: 'org_imbrace',
    channel_id: 'ch_312cf186-0c72-48a7-8981-ea9a764ce33e',
    channel_type: 'web',
    display_name: 'Jenny Wong',
    avatar_url: DummyAvatar,
    first_name: '',
    last_name: '',
    gender: '',
    area_code: '',
    phone_number: '',
    language: 'en',
    email: '',
    remark: '',
    time_zone: 'Asia/Taipei',
    last_seen: '',
    title: '',
    birthday: '',
    location: '',
    company_name: '',
    whatsapp_id: '',
    facebook_id: '',
    messenger_id: '',
    wechat_id: '',
    line_id: '',
    instagram_id: '',
};
export const dummyConversation: ReduxTeamConversations = {
    _id: 'sample_team_conv',
    id: 'sample_team_conv',
    object_name: 'team_conversation',
    channel_id: '',
    contact_id: '',
    organization_id: 'org_imbrace',
    business_unit_id: 'bu_imbrace_testing',
    team_id: 't_imbrace_default_team',
    conversation_id: 'sample_conv',
    latest_message: {
        object_name: 'message',
        organization_id: '',
        business_unit_id: '',
        conversation_id: '',
        id: 'dummy_msg',
        type: 'text',
        content: {
            text: 'Customer support',
            is_mail: false,
        },
        created_at: `${new Date().toISOString()}`,
        is_bot: false,
        from: '',
        updated_at: `${new Date().toISOString()}`,
    },
    conversation: {
        id: 'sample_conv',
        object_name: 'conversation',
        organization_id: 'org_imbrace',
        business_unit_id: 'bu_imbrace_testing',
        channel_id: 'sample_channel',
        channel_type: 'web',
        contact_id: 'sample_contact',
        status: 'pending',
        name: 'Jenny Wong',
        timestamp: '2024-03-18T09:04:21.315Z',
        is_agent_joined: true,
        is_joined: false,
    },
    contact: dummyContact,
    is_joined: true,
    channel: {
        _id: 'sample_channel',
        name: 'Web',
        active: true,
        is_deleted: false,
    },
    is_presence: true,
    name: 'Jenny Wong',
    status: 'pending',
    timestamp: `${new Date().toISOString()}`,
    is_agent_joined: true,
    channel_type: 'web',
    team_name: 'General',
};

const dummyBotUser: API.User = {
    object_name: 'user',
    id: 'u_imbrace_bot',
    _id: 'u_imbrace_bot',
    organization_id: 'org_imbrace',
    email: '',
    role: 'bot',
    team_ids: [],
    time_zone: '',
    last_seen: '',
    company_name: '',
    location: '',
    title: '',
    birthday: '',
    display_name: 'Bot',
    avatar_url: '',
    first_name: '',
    last_name: '',
    gender: '',
    area_code: '',
    phone_number: '',
    language: 'en',
    status: 'active',
    is_bot: true,
    is_active: true,
    is_archived: false,
    created_at: '2022-01-04T03:26:24.743Z',
    updated_at: '2022-01-04T03:26:24.743Z',
};

// eslint-disable-next-line
const dummyAdminUser: API.User = {
    object_name: 'user',
    id: 'sample_user',
    _id: 'sample_user',
    organization_id: 'org_imbrace',
    email: '',
    role: 'bot',
    team_ids: [],
    time_zone: '',
    last_seen: '',
    company_name: '',
    location: '',
    title: '',
    birthday: '',
    display_name: 'Amanda',
    avatar_url: '',
    first_name: '',
    last_name: '',
    gender: '',
    area_code: '',
    phone_number: '',
    language: 'en',
    status: 'active',
    is_bot: false,
    is_active: true,
    is_archived: false,
    created_at: '2022-01-04T03:26:24.743Z',
    updated_at: '2022-01-04T03:26:24.743Z',
};

export const dummyTeamConv: API.TeamConversation & { presenceTime?: string } = {
    ...dummyConversation,
    users: [
        {
            object_name: 'simple_user',
            id: 'u_imbrace_bot',
            is_bot: true,
            display_name: 'Bot',
            avatar_url: '',
            first_name: '',
            last_name: '',
        },
        {
            display_name: 'Amanda',
            object_name: 'simple_user',
            id: 'sample_user',
            avatar_url: '',
            first_name: '',
            last_name: 'Amanda',
            is_bot: false,
        },
    ],
};

export const dummyComment = {
    _id: 'sample_comments',
    content:
        'We need to check our internal system and update the customer via email in 3 days. @Tony please ensure this is done and update me. Thanks',
    channel_type: 'web',
    labels: [
        {
            color: '#CA3476',
            _id: 'sample_label',
            business_unit_id: '',
            organization_id: '',
            name: 'Shipping Issue',
            public_id: '',
            team_id: '',
            doc_name: '',
        },
    ],
    from: {
        _id: 'sample_user',
        display_name: 'Amanda',
    },
    created_at: `${new Date().toISOString()}`,
    updated_at: `${new Date().toISOString()}`,
};

export const dummyMessages: (ReduxMessage & {
    contact?: API.User | API.Contact;
})[] = [
    {
        id: 'sample_msg_1',
        object_name: 'message',
        organization_id: 'org_default',
        from: 'sample_contact',
        type: 'text',
        business_unit_id: 'bu_imbrace_testing',
        created_at: `${new Date().toISOString()}`,
        updated_at: `${new Date().toISOString()}`,
        conversation_id: 'sample_conv',
        content: {
            text: 'Hi',
            is_mail: false,
        },
        contact: dummyContact,
    },
    {
        id: 'sample_msg_2',
        object_name: 'message',
        organization_id: 'org_default',
        from: 'u_imbrace_bot',
        type: 'text',
        business_unit_id: 'bu_imbrace_testing',
        created_at: `${new Date().toISOString()}`,
        updated_at: `${new Date().toISOString()}`,
        conversation_id: 'sample_conv',
        content: {
            text: 'Hi there, how can I help you today?',
            is_mail: false,
        },
        contact: dummyBotUser,
    },
    {
        id: 'sample_msg_3',
        object_name: 'message',
        organization_id: 'org_default',
        from: 'sample_contact',
        type: 'text',
        business_unit_id: 'bu_imbrace_testing',
        created_at: `${new Date().toISOString()}`,
        updated_at: `${new Date().toISOString()}`,
        conversation_id: 'sample_conv',
        content: {
            text: 'I still haven’t received my package yet, can you help me to check the shipping status?',
            is_mail: false,
        },
        comments: [dummyComment],
    },
    {
        object_name: 'message',
        id: 'sample_msg_4',
        organization_id: 'org_imbrace',
        business_unit_id: 'bu_imbrace_testing',
        conversation_id: 'sample_conv',
        from: 'u_imbrace_bot',
        type: 'response',
        content: {
            title: 'View List',
            text: 'What can i help you?',
            quick_replies: [
                {
                    id: '0',
                    content_type: 'text',
                    title: 'What can i help you?',
                    description: '',
                    payload: '0_Set Workflow Language',
                },
                {
                    id: '1',
                    content_type: 'text',
                    title: 'Product Updates',
                    description: '',
                    payload: '1_Set Workflow Language',
                },
                {
                    id: '2',
                    content_type: 'text',
                    title: 'Others',
                    description: '',
                    payload: '2_Set Workflow Language',
                },
            ],
        },
        created_at: `${new Date().toISOString()}`,
        updated_at: `${new Date().toISOString()}`,
        contact: dummyBotUser,
    },
];
